### ISSUE TITLE
Default VPC only

### ISSUE THREAD

**Issue by rojata** [ansible-community/molecule-ec2#5]
When creating a scenario, there are "not enough" options to allow one to create a "test" environment in a non default VPC from an AWS standpoint which could lead to issues, i.e., target test instance not being able to be created.

In my "project", I did enrich the yaml files as follows:

molecule.yaml 
```yaml
---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-12345678910
    instance_type: t2.micro
    vpc_subnet_id: subnet-2345678911 # must belong to VPC_ID below
    vpc_id: vpc-345678912
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
```

and then in the create.yaml, I added the vpc_id as part of one of the parameter for the creation of the security group:
```yaml
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        vpc_id: "{{ item.vpc_id }}"
        description: "{{ security_group_name }}"
        rules: "{{ security_group_rules }}"
        rules_egress: "{{ security_group_rules_egress }}"
      with_items: "{{ molecule_yml.platforms }}"
```

Happy to work on the same.
