### ISSUE TITLE
Dynamic inventory not supported for ec2?

### ISSUE THREAD

**Issue by bedge** [ansible-community/molecule-ec2#50]
I have inventories generated on the fly from ec2 tags, eg:
```
[I] ➜ ansible-inventory -i inventory_aws_ec2.yml --graph
@all:
  |--@app_Bastion:
  |  |--xxx-dev1-bastion
  |  |--xxx-dev2-bastion
  |  |--xxx-dev3-bastion
....
```

Using this `inventory_aws_ec2.yml`:

```yaml
plugin: aws_ec2

regions:
  - eu-central-1

filters:
  tag:Project:
    - XXX
  instance-state-name : running

strict_permissions: False

strict: False
keyed_groups:
  - key: tags.App
    separator: ''
    prefix: 'app_'
  - key: tags.Name
    separator: ''
    prefix: 'name_'
  - key: tags.Environment
    separator: ''
    prefix: 'env_'
hostnames:
  - tag:Name
  - ip-address
  - dns-name
  - private-ip-address

compose:
  ansible_host: instance_id
```
I must be missing something as it appears that the molecule-ec2 only supports static inventory files?
