### ISSUE TITLE
Add the ability to specify arbitrary search filter

### ISSUE THREAD

**Issue by beargiles** [ansible-community/molecule-ec2#72]
The documentation has an example of specifying an AMI via the product code. It doesn't seem to work but I have submitted a PR to fix this. 

[Improved flexibility for image_filters in create.yml](https://github.com/ansible-community/molecule-ec2/pull/71)

You can now use

```
platforms:

  - name: molecule-test
    image_owner: '$UBUNTU_ACCOUNT_ID'
    image_filters:
      'product-code': '$UBUNTU_2204_PRODUCT_CODE'
      'product-code.type': marketplace
    region: us-west-2
    ...
```

where the role's directory contains an .env.yml file containing

```
UBUNTU_ACCOUNT_ID: '679593333241'
UBUNTU_2204_PRODUCT_CODE: '47xbq...'
```

Note: the product code is the value you get after successfully subscribing to the product and creating an instance in the desired region. (You can get the product id from the instance's metadata.) If you specify the marketplace product id you'll get an error message saying you need to subscribe to the product.
